/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js conventions and is intentionally tracked
// to keep qualification from introducing an untracked compiler surface.
