import { readFile, stat } from "node:fs/promises";

const required = [
  "ggen.toml",
  "ontology/ggen-ui.ttl",
  "src/generated/dashboard-contract.ts",
  "src/generated/dashboard-contract.json",
  "src/generated/projections.ts",
  "src/generated/semantic-tokens.css",
  "src/lib/brce.ts",
];

for (const path of required) {
  const info = await stat(path);
  if (!info.isFile() || info.size === 0) throw new Error(`REFUSED:REQUIRED_FILE:${path}`);
}

const generatedTs = await readFile("src/generated/dashboard-contract.ts", "utf8");
const generatedJson = JSON.parse(await readFile("src/generated/dashboard-contract.json", "utf8"));
const projections = await readFile("src/generated/projections.ts", "utf8");
const brce = await readFile("src/lib/brce.ts", "utf8");

if (!generatedTs.includes("GENERATED BY ggen-dashboard-pack")) throw new Error("REFUSED:UNTRACED_GENERATED_CONTRACT");
if (!projections.includes("GENERATED BY ggen-dashboard-pack")) throw new Error("REFUSED:UNTRACED_GENERATED_PROJECTIONS");
if (generatedJson.schema !== "https://ggen.io/schema/dashboard-contract/v1") throw new Error("REFUSED:CONTRACT_SCHEMA");
if (generatedJson.brceRequired !== true) throw new Error("REFUSED:BRCE_NOT_REQUIRED");

const doStages = generatedJson.authorityStages.filter((stage) => stage.allowsDo === true);
if (doStages.length !== 1 || doStages[0].code !== "BRCE") throw new Error("REFUSED:DO_AUTHORITY_TOPOLOGY");
const doIntents = generatedJson.intentKinds.filter((intent) => intent.allowsDo === true);
if (doIntents.length !== 1 || doIntents[0].code !== "ACTUATE_VIA_BRCE") throw new Error("REFUSED:INTENT_AUTHORITY_TOPOLOGY");
if (generatedJson.projections.length < 7) throw new Error("REFUSED:PROJECTION_COVERAGE");
if (/\bfetch\s*\(|\baxios\b|XMLHttpRequest/.test(brce)) throw new Error("REFUSED:AMBIENT_NETWORK_ACTUATION");
if (!brce.includes("BLOCKED:NO_BRCE_TRANSPORT")) throw new Error("REFUSED:TRANSPORT_FAIL_CLOSED");

console.log(JSON.stringify({
  standing: "PARTIAL_ALIVE",
  verified: ["generated-contract", "generated-projections", "brce-exclusive-do", "fail-closed-transport", "projection-coverage"],
  authorityCeiling: "CONSTRUCT_WITH_EXPLICIT_BRCE_TRANSPORT",
  projections: generatedJson.projections.length,
}, null, 2));
